### ISSUE TITLE
Can't set fields on Android

### ISSUE THREAD

**Issue by MatFl** [dpreussler/SuperReflect#2]
On Android the `Field` class doesn't have a `modifiers` field.
See: https://android.googlesource.com/platform/libcore/+/895bba4/libdvm/src/main/java/java/lang/reflect/Field.java

That's why the [`removeFinal`](https://github.com/dpreussler/SuperReflect/blob/master/src/main/java/de/jodamob/reflect/SuperReflect.java#L243-L250) method fails. The final fields can actually be set without removing the modifiers. Maybe a simple catch around `Field.class.getDeclaredField("modifiers")` would already be enough. On standard java this should never fail, right?

**Comment by dpreussler** [comment]
thanks for letting me know. 
Fixed, seems to work.
I pushed a version 1.0.1 to maven central, should be available in the next 24hours

Its already on staging:
maven { url 'https://oss.sonatype.org/content/repositories/staging' }

**Comment by MatFl** [comment]
Thanks for the quick fix. Seems to be working fine now.
